- modules/drivers/spi/api/rtos_spi_master.h
- modules/drivers/spi/src/rtos_spi_master.c
> Locks spi io thread to core for transaction duration

- modules/drivers/i2c/api/rtos_i2c_slave.h
- modules/drivers/i2c/src/rtos_i2c_slave.c
> Adds ability for I2C slave to ack/nack per byte

- modules/drivers/i2c/api/rtos_i2c_slave.h
- modules/drivers/i2c/src/rtos_i2c_slave.c
> Add callback for write request start

- tools/cmake_utils/xmos_macros.cmake
Adds query_tools_version
Adds an install target
closes https://github.com/xmos/fwk_rtos/issues/61
closes https://github.com/xmos/fwk_rtos/issues/62
> CMake macro enhancements

- tools/cmake_utils/xmos_macros.cmake
Consolidates CMake macros for general purpose use.
Also removes print from query tools version.
> Consolidate cmake macros

- modules/drivers/spi/api/rtos_spi_slave.h
- modules/drivers/spi/src/rtos_spi_slave.c
https://github.com/xmos/sw_xvf3800/issues/437
> SPI driver changes to handle control commands received at driver startup

- test/rtos_drivers/usb/src/individual_tests/usb/local/usb_descriptors.c
Update USB PIDs to adhere to:
https://xmosjira.atlassian.net/wiki/spaces/UAAI/pages/3592290309/Product+ID+s
> Update usb PIDs

- doc/build_system_guide/cmakelists.rst
- doc/build_system_guide/index.rst
- doc/build_system_guide/introduction.rst
- doc/build_system_guide/macros.rst
- doc/build_system_guide/targets.rst
- doc/programming_guide/tutorials/application_design.rst
Closes https://github.com/xmos/fwk_rtos/issues/59
> updated build system docs

- modules/sw_services/tls_support/CMakeLists.txt
Verified with example_freertos_iot in xcore_iot
> Update to v2.28.3 from 2.16.6

- modules/drivers/qspi_flash/api/rtos_qspi_flash.h
- modules/drivers/qspi_flash/src/rtos_qspi_flash.c
- test/rtos_drivers/hil_add/src/individual_tests/qspi_flash/local/lowlevel_api_test.c
- test/rtos_drivers/hil_add/src/individual_tests/qspi_flash/qspi_flash_test.c
- test/rtos_drivers/hil_add/src/individual_tests/qspi_flash/qspi_flash_test.h
- test/rtos_drivers/hil_add/src/individual_tests/qspi_flash/rpc/read_write_read_mode_test.c
- test/rtos_drivers/hil_add/src/individual_tests/qspi_flash/rpc/read_write_read_test.c
- tools/ci/fetch_ci_deps.cmake
Adds flash driver low level mode variant, adds low level shutdown.
Fixes flash tests.
> Add more ll updates

- modules/sw_services/mqtt/FreeRTOS/MQTTFreeRTOS.c
- modules/sw_services/tls_support/CMakeLists.txt
Verified on Linux with xcore_iot iot application.
> Update mbedtls with functional mqtt

- test/rtos_drivers/hil_add/check_drivers_hil_add.sh
introduced in #172
Hopefully will bring Jenkins back to green.
> Ensure we flash a specific xtag id in hil_add test

- modules/drivers/qspi_flash/src/rtos_qspi_flash.c
> Add retry behavior for libquadflash connect

- modules/drivers/usb/api/rtos_usb.h
https://github.com/xmos/sw_xvf3800/issues/935
> Implement set and clear stall when using the proxy

- modules/drivers/i2c/src/rtos_i2c_master_rpc.c
- test/rtos_drivers/hil/src/individual_tests/i2c/rpc/master_write_multiple_test.c
https://xmosjira.atlassian.net/browse/AP-163
https://xmosjira.atlassian.net/browse/AP-164
> i2c_master_remote_write() nullptr fix

- CHANGELOG.rst
- tools/ci/fetch_ci_deps.cmake
* UPDATED: To fwk_io v3.3.0 from v3.0.1 for CI run
* UPDATED: To fwk_core v1.0.2 from v1.0.0 for CI run
> Bump fwk_core and fwk_io in CI run

- CHANGELOG.rst
- modules/drivers/i2s/api/rtos_i2s.h
- modules/drivers/i2s/src/rtos_i2s.c
- modules/drivers/i2s/src/rtos_i2s_rpc.c
https://xmosjira.atlassian.net/browse/AP-157
> Added a runtime check for RPC being set up for I2S Slave case

- CHANGELOG.rst
Part of https://xmosjira.atlassian.net/browse/AP-236
> Use tag v1.0.0 for xmos_cmake_toolchain

- test/rtos_drivers/clock_control/check_clock_control.sh
- test/rtos_drivers/hil/check_drivers_hil.sh
- test/rtos_drivers/hil/src/individual_tests/qspi_flash/local/read_write_read_test.c
- test/rtos_drivers/hil_add/check_drivers_hil_add.sh
- test/rtos_drivers/wifi/check_wifi.sh
https://xmosjira.atlassian.net/browse/AP-245
> Fix RTOS test failures

- CHANGELOG.rst
- modules/sw_services/device_control/transport/spi/device_control_spi.c
Needed for https://github.com/xmos/fwk_xvf/issues/36
> Increase SPI tx/rx buffer sizes

- CHANGELOG.rst
- Jenkinsfile
- modules/sw_services/device_control/host/device_access_usb.c
closes (partially): [AP-496](https://xmosjira.atlassian.net/browse/AP-496?atlOrigin=eyJpIjoiZjYzZWZjZDVjOGQ4NDNhYTk3NjM2YWZmZjU4ZjkwYjgiLCJwIjoiaiJ9)
[AP-496]: https://xmosjira.atlassian.net/browse/AP-496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fixing stdbool vor older windows versions

- CHANGELOG.rst
> Updates for release v3.2.0
